### ISSUE TITLE
Invalid Name

### ISSUE THREAD

**Issue by Achim-Sommer** [HumanTree92/esx_advancedbanking#3]
**Describe the Bug | A Clear & Concise Description of Bug**

The credit balance is now displayed. Thanks
But now the following is written on the left side above.

Hello, **Invalid**

I think the player name should be there.

**Questions**
Have you looked through the Closed Topics?:  YES
Have you looked through the Wiki?: YES
What Version of es_extended are you using?: 1.2
Are you using a Pre-Installed ESX?: NO
Are you using Essentialmode?: NO
Are you using OneSync?: YES
Linux or Windows?: Windows Server & Linux Server

**Comment by HumanTree92** [comment]
Try using es_extended V1 Final. 1.2 is over 200 commits short. Make sure you edit the config.lua by default everything is turn off. Try Setting Config.ShowCharName = false to true
